var OWN = {
 app:["config","Your main class: @SpringBootApplication (= @Configuration + @EnableAutoConfiguration + @ComponentScan) calling SpringApplication.run."],
 ctxc:["spring","Boot picks the context type from the classpath (servlet web app here)."],
 refresh:["spring","Never called by you in a Boot app."],
 ccpp:["config","Driven by YOUR annotations: @Component/@Service/@Repository/@Controller on classes in the main class's package or below, @Configuration classes with @Bean methods, @Import."],
 autoconf:["spring","Comes from starters on the classpath. Control it with properties or by defining your own bean of the same type; exclude with @SpringBootApplication(exclude=…)."],
 cond:["config","You influence it: define your own bean → @ConditionalOnMissingBean backs off; set properties; @Profile on your beans. Debug with --debug (conditions report)."],
 bdmap:["spring","Filled from your annotations; you rarely touch it directly."],
 bfpp:["spring","Boot registers the needed ones. Write your own only for framework-level tricks; declare it as a static @Bean."],
 bppreg:["spring","Boot/Spring register them. Write a BeanPostProcessor only for cross-cutting container tricks (rare)."],
 presing:["spring","Every non-lazy singleton is created at startup, so wiring errors fail fast. spring.main.lazy-initialization=true changes that (not recommended for prod)."],
 ready:["config","Hook in with an ApplicationRunner/CommandLineRunner bean or @EventListener(ApplicationReadyEvent.class)."],
 close:["spring","Boot registers the JVM shutdown hook. server.shutdown=graceful waits for in-flight requests (the default since Boot 3.4)."],
 getbean:["spring","You don't call getBean in normal code; injection does it."],
 cache:["spring","Internal. You only feel it through circular-reference behaviour."],
 inst:["write","Your class and its constructor. Prefer constructor injection (final fields); one constructor needs no @Autowired."],
 mbdpp:["spring","Reads your @Autowired, @Value, @Resource, @PostConstruct, @PreDestroy annotations."],
 populate:["config","Only used if you inject by field/setter (@Autowired on a field). With constructor injection this step has nothing to inject."],
 resolve:["config","You control the choice with @Qualifier(\"name\"), @Primary on one bean, or by injecting List<T>, Optional<T>, ObjectProvider<T>."],
 aware:["config","Implement ApplicationContextAware etc. only if you truly need the container; usually just inject what you need."],
 before:["write","Your @PostConstruct method: validation or warm-up that needs injected dependencies. This bean has no proxy yet, so its OWN @Transactional methods called here run without a transaction (calling another bean's @Transactional method is fine)."],
 init:["config","InitializingBean or @Bean(initMethod=…); @PostConstruct is usually enough."],
 after:["spring","Proxies appear here because you used @Transactional, @Async, @Cacheable, @PreAuthorize or an @Aspect."],
 singleton:["spring","Default scope. Change with @Scope."],
 destroy:["write","Your @PreDestroy method (close clients, flush buffers). @Bean methods can use destroyMethod."],
 apc:["config","Exists because of spring-boot-starter-aop / @EnableTransactionManagement (auto-configured). Proxy type: spring.aop.proxy-target-class."],
 advisors:["config","Your annotations create the matches: @Transactional, @PreAuthorize, @Cacheable, @Async, or your @Aspect pointcuts. Order with @Order on aspects."],
 pf:["spring","Internal."],
 cglib:["config","Default in Boot. Keep classes and proxied methods non-final (Kotlin: all-open / kotlin-spring plugin)."],
 jdk:["config","Only if spring.aop.proxy-target-class=false and the bean implements an interface; then inject the interface type."],
 proxy:["spring","You never write it; you just inject the bean and get the proxy."],
 chain:["spring","Internal."],
 aspect:["write","Your @Aspect @Component class with @Around(\"@annotation(com.x.LogTime)\") etc. Needs spring-boot-starter-aop."],
 secint:["config","@EnableMethodSecurity + @PreAuthorize(\"hasAuthority('SCOPE_payment.write')\") on your methods."],
 asyncint:["config","@EnableAsync on a @Configuration + @Async on a PUBLIC method of another bean. Tune spring.task.execution.* or define your own executor."],
 txi:["config","Exists because you put @Transactional on a class or public/protected method (Boot enables transaction management automatically)."],
 tas:["config","Your @Transactional attributes: propagation, isolation, readOnly, timeout, rollbackFor."],
 tm:["spring","Auto-configured (JpaTransactionManager). Define your own only for multiple data sources (then @Transactional(\"txManagerName\"))."],
 tsm:["spring","You can read it (TransactionSynchronizationManager.isActualTransactionActive()) for debugging."],
 conn:["config","spring.datasource.* and spring.datasource.hikari.maximum-pool-size."],
 em:["spring","Injected into repositories. You rarely use EntityManager directly."],
 flush:["spring","Automatic. Call repository.flush()/saveAndFlush only when you need SQL errors inside the method."],
 db:["ext","Your database (H2 in Service B)."],
 osiv:["config","spring.jpa.open-in-view. Set it to false for APIs and fetch what you need inside the transaction."],
 sync:["spring","Registered for you by @TransactionalEventListener; you can register your own TransactionSynchronization (rare)."],
 env:["config","Your application.yml, profiles (spring.profiles.active), @Value(\"${…}\") and @ConfigurationProperties classes."],
 cfgclass:["config","Your @Configuration classes. Boot's own auto-configs use proxyBeanMethods=false."],
 scope:["config","@Scope(\"prototype\"), @RequestScope, @SessionScope on your beans; ObjectProvider<T> or @Lookup when a singleton needs a fresh instance."],
 lazy:["config","@Lazy on a bean or injection point; spring.main.lazy-initialization."],
 fb:["spring","You rarely write one; Spring Data and many libraries do."],
 events:["config","Inject ApplicationEventPublisher and call publishEvent(new PaymentCreated(…))."],
 executor:["config","spring.task.execution.pool.* or your own ThreadPoolTaskExecutor bean; add a TaskDecorator to copy MDC/SecurityContext."],
 ctrl:["write","Your controller."],
 svc:["write","Your service with @Transactional on public methods."],
 svc2:["write","Your second service with @Transactional(propagation = REQUIRES_NEW)."],
 repo:["write","Your interface extending JpaRepository; Spring generates the implementation."],
 listener:["write","Your @EventListener or @TransactionalEventListener(phase = AFTER_COMMIT) method."],
 target:["write","Your class, as you wrote it; the proxy wraps it."]
};
