var NODES = [
 // ---- launch ----
 ["jar","Executable jar","JarLauncher (spring-boot-loader)",20,45,180,"launch","java -jar app.jar: MANIFEST Main-Class = org.springframework.boot.loader.launch.JarLauncher (Boot 3.2+ package), Start-Class = your main class. Loads nested jars from BOOT-INF/lib with LaunchedClassLoader."],
 ["main","Your main()","SpringApplication.run",20,85,180,"launch","Your class annotated @SpringBootApplication calls SpringApplication.run(App.class, args)."],
 ["sa","new SpringApplication","SpringApplication constructor",20,125,180,"launch","Deduces WebApplicationType from the classpath (SERVLET / REACTIVE / NONE), loads ApplicationContextInitializers and ApplicationListeners from META-INF/spring.factories, finds the main class."],
 ["listeners","Run listeners → events","EventPublishingRunListener",20,165,180,"launch","Publishes the startup events in order: Starting → EnvironmentPrepared → ContextInitialized → Prepared → Started → Ready (or Failed)."],
 ["failure","Failure analysis","FailureAnalyzers",20,205,180,"launch","If run() throws, FailureAnalyzers turn the exception into the 'APPLICATION FAILED TO START' report with Description and Action."],
 // ---- environment ----
 ["env","Environment","ApplicationServletEnvironment",230,45,190,"env","Holds all PropertySources and the active profiles. Created and prepared before the ApplicationContext exists."],
 ["envpp","EnvironmentPostProcessors","EnvironmentPostProcessorApplicationListener",230,85,190,"env","Run on ApplicationEnvironmentPreparedEvent. The most important one loads config files (ConfigDataEnvironmentPostProcessor)."],
 ["cfgdata","Config data","ConfigDataEnvironmentPostProcessor",230,125,190,"env","Loads application.yml / .properties from classpath and ./config, then application-{profile}.yml, plus spring.config.import sources."],
 ["propsrc","Property source order","first match wins",230,165,190,"env","Highest first (simplified): command-line args > Java system properties > OS env vars > application-{profile}.yml > application.yml > @PropertySource > defaults. Files outside the jar beat files inside."],
 ["profiles","Profiles","spring.profiles.active / group",230,205,190,"env","Decide which application-{profile}.yml files load and which @Profile beans exist. Groups: spring.profiles.group.prod=db,metrics."],
 ["binder","Binder","relaxed binding",230,245,190,"env","Binds properties to objects. Relaxed: payment.max-amount, payment.maxAmount and PAYMENT_MAXAMOUNT all bind to maxAmount."],
 // ---- context & auto-config ----
 ["ctx","ApplicationContext","AnnotationConfigServletWebServer…",440,45,200,"ctx","Created by ApplicationContextFactory for WebApplicationType.SERVLET, then refresh() runs (see Spring Core)."],
 ["sba","@SpringBootApplication","= 3 annotations",440,85,200,"ctx","@SpringBootConfiguration (@Configuration) + @EnableAutoConfiguration + @ComponentScan (package of the main class and below)."],
 ["ccpp","ConfigurationClassPostProcessor","reads your config first",440,125,200,"ctx","Parses your classes (scan, @Bean, @Import), then the deferred auto-configuration imports."],
 ["selector","AutoConfigurationImportSelector","DeferredImportSelector",440,165,200,"ctx","Behind @EnableAutoConfiguration. Deferred = runs after your configuration is known, so auto-config can back off."],
 ["imports","AutoConfiguration.imports","META-INF/spring/…AutoConfiguration.imports",440,205,200,"ctx","Each auto-configure jar lists its @AutoConfiguration classes in this file (Boot 3; the old spring.factories key is gone). ~150 candidates."],
 ["filter","Fast pre-filter","AutoConfigurationImportFilter",440,245,200,"ctx","OnClassCondition / OnWebApplicationCondition / OnBeanCondition check precomputed metadata (spring-autoconfigure-metadata.properties) to drop most candidates without loading their classes."],
 ["cond","Conditions","@ConditionalOn…",440,285,200,"ctx","@ConditionalOnClass, @ConditionalOnMissingBean, @ConditionalOnProperty, @ConditionalOnWebApplication, @ConditionalOnBean. Evaluated per class and per @Bean method."],
 ["report","Conditions report","ConditionEvaluationReport",440,325,200,"ctx","Records why each auto-config matched or not. Printed with --debug, or GET /actuator/conditions."],
 // ---- examples ----
 ["starter","Starter","spring-boot-starter-*",660,45,200,"auto","A starter is only a pom of dependencies (e.g. starter-web = spring-webmvc + tomcat + jackson). Putting classes on the classpath is what triggers auto-config."],
 ["webauto","Web server auto-config","ServletWebServerFactoryAutoConfiguration",660,85,200,"auto","Creates TomcatServletWebServerFactory (if Tomcat is on the classpath and you didn't define a factory), applies server.* properties."],
 ["mvcauto","MVC auto-config","DispatcherServletAutoConfiguration, WebMvcAutoConfiguration",660,125,200,"auto","Registers the DispatcherServlet (DispatcherServletRegistrationBean), message converters, static resources, error handling (/error)."],
 ["dsauto","DataSource auto-config","DataSourceAutoConfiguration",660,165,200,"auto","If there is no DataSource bean: builds HikariDataSource from spring.datasource.* (or an embedded H2 when no URL is set)."],
 ["jpaauto","JPA auto-config","HibernateJpaAutoConfiguration",660,205,200,"auto","EntityManagerFactory, JpaTransactionManager, entity scanning, spring.jpa.* properties, Open Session In View interceptor."],
 ["jacksonauto","Jackson auto-config","JacksonAutoConfiguration",660,245,200,"auto","Builds the ObjectMapper from spring.jackson.* and any Jackson2ObjectMapperBuilderCustomizer beans."],
 ["secauto","Security auto-config","SecurityAutoConfiguration, UserDetailsService…",660,285,200,"auto","No SecurityFilterChain of yours → default chain: everything authenticated with form login + basic (or oauth2ResourceServer(jwt) when issuer-uri is set). No user setup and no OAuth2 classes → user 'user' with a generated password in the log."],
 ["rsauto","Resource server auto-config","OAuth2ResourceServerAutoConfiguration",660,325,200,"auto","spring.security.oauth2.resourceserver.jwt.issuer-uri set → JwtDecoder bean. It contacts the issuer lazily on first use (SupplierJwtDecoder), so the Auth Server needn't be up at startup."],
 // ---- server & lifecycle ----
 ["wsf","Create web server","ServletWebServerApplicationContext.onRefresh",880,45,190,"life","During refresh(): factory.getWebServer(...) creates Tomcat and runs ServletContextInitializers (registers DispatcherServlet and filter beans). Not listening yet."],
 ["customizer","Customizers","WebServerFactoryCustomizer",880,85,190,"life","Beans that tweak auto-configured objects without replacing them (web server, ObjectMapper builder, RestClient builder…)."],
 ["wsstart","Web server starts","WebServerStartStopLifecycle",880,125,190,"life","SmartLifecycle started in finishRefresh(): connectors bound → 'Tomcat started on port 8081 (http)'."],
 ["runners","Runners","ApplicationRunner / CommandLineRunner",880,165,190,"life","Called after the context is started, before ApplicationReadyEvent."],
 ["avail","Availability state","ApplicationAvailability",880,205,190,"life","LivenessState.CORRECT after start; ReadinessState.ACCEPTING_TRAFFIC after ready; REFUSING_TRAFFIC during graceful shutdown."],
 ["shutdown","Shutdown","SpringApplicationShutdownHook",880,245,190,"life","JVM shutdown hook → context.close(). Graceful by default since Boot 3.4: stops accepting requests, waits up to spring.lifecycle.timeout-per-shutdown-phase (30s)."],
 // ---- actuator ----
 ["actauto","Actuator","spring-boot-starter-actuator",1090,45,190,"act","Auto-configures endpoints under /actuator. Over HTTP only /actuator/health is exposed by default."],
 ["exposure","Exposure","management.endpoints.web.exposure.include",1090,85,190,"act","Which endpoints are reachable over HTTP (health, info, metrics, prometheus, conditions, env…). Exposing env/beans in prod leaks internals."],
 ["health","Health endpoint","HealthEndpoint",1090,125,190,"act","Aggregates HealthContributors (db, diskSpace, ping…). DOWN → HTTP 503. Details hidden by default (show-details=never)."],
 ["dbhealth","DB health check","DataSourceHealthIndicator",1090,165,190,"act","Borrows a connection and validates it. Database down → status DOWN."],
 ["probes","Liveness / readiness","/actuator/health/liveness, /readiness",1090,205,190,"act","Health groups for Kubernetes probes, built from ApplicationAvailability. Enabled automatically on Kubernetes/Cloud Foundry or with management.endpoint.health.probes.enabled=true."],
 ["metrics","Metrics","MeterRegistry (Micrometer)",1090,245,190,"act","/actuator/metrics and /actuator/prometheus: JVM, HTTP server requests, Hikari pool, custom meters."],
 // ---- your code ----
 ["app","@SpringBootApplication class","your main class",20,560,190,"you","The class with main(). Its package is the root for component scanning."],
 ["yml","application.yml","your config files",230,560,190,"you","Ports, datasource, security issuer, logging, management.* settings, per profile."],
 ["props","@ConfigurationProperties","your typed settings",440,560,190,"you","A record/class bound from a prefix, e.g. payment.max-amount → PaymentProperties.maxAmount."],
 ["yourbean","Your @Bean overrides","your @Configuration",650,560,190,"you","Defining a bean of the same type makes the auto-config back off (@ConditionalOnMissingBean)."],
 ["mystarter","Your own auto-config","@AutoConfiguration in a library",860,560,190,"you","A shared library that auto-configures itself in every service that adds it."]
];
var GROUPS = [
 ["Launch",10,22,200,230],["Environment & properties",220,22,210,270],["Context & auto-config",430,22,220,340],
 ["Auto-configurations (examples)",650,22,220,340],["Web server & lifecycle",870,22,210,270],["Actuator",1080,22,210,270],
 ["Your code",10,540,1270,60]
];
var OWN = {
 jar:["config","Built by spring-boot-maven-plugin (repackage goal) when you run mvn package."],
 main:["write","Your main method; usually just SpringApplication.run(App.class, args)."],
 sa:["spring","You can customise it: new SpringApplication(App.class).setBannerMode(...) or SpringApplicationBuilder."],
 listeners:["config","Listen with @EventListener(ApplicationReadyEvent.class) etc. Events before the context exists need listeners registered in spring.factories or via SpringApplication.addListeners."],
 failure:["spring","Automatic. You can add your own FailureAnalyzer in spring.factories (rare)."],
 env:["spring","Inject Environment only if you really need it; prefer @ConfigurationProperties."],
 envpp:["spring","You rarely write one (registered in spring.factories)."],
 cfgdata:["config","Your application.yml files and spring.config.import (e.g. configserver:, optional:file:)."],
 propsrc:["config","You override by environment variables or command-line args at deploy time (SPRING_DATASOURCE_PASSWORD=...)."],
 profiles:["config","spring.profiles.active=dev, application-dev.yml, @Profile(\"dev\") on beans."],
 binder:["spring","Used automatically for @ConfigurationProperties and spring.* settings."],
 ctx:["spring","Chosen from the classpath."],
 sba:["write","One annotation on your main class. Keep the main class in the root package."],
 ccpp:["spring","Reads your annotations."],
 selector:["spring","Enabled by @SpringBootApplication; exclude with @SpringBootApplication(exclude = X.class) or spring.autoconfigure.exclude."],
 imports:["spring","Inside Boot's jars (and your own starter's jar)."],
 filter:["spring","Internal speed-up."],
 cond:["config","Your beans and properties decide the outcome."],
 report:["config","Run with --debug or enable the conditions actuator endpoint when something 'isn't created'."],
 starter:["config","Your pom dependencies: spring-boot-starter-web, -data-jpa, -security, -oauth2-resource-server, -validation, -actuator."],
 webauto:["config","server.port, server.servlet.context-path, server.tomcat.*"],
 mvcauto:["config","spring.mvc.*; add a WebMvcConfigurer bean to extend (don't use @EnableWebMvc, it switches Boot's MVC config off)."],
 dsauto:["config","spring.datasource.url/username/password, spring.datasource.hikari.*"],
 jpaauto:["config","spring.jpa.hibernate.ddl-auto, spring.jpa.show-sql, spring.jpa.open-in-view"],
 jacksonauto:["config","spring.jackson.* or a Jackson2ObjectMapperBuilderCustomizer bean."],
 secauto:["config","Define your own SecurityFilterChain bean → the default chain backs off."],
 rsauto:["config","spring.security.oauth2.resourceserver.jwt.issuer-uri (or jwk-set-uri)."],
 wsf:["spring","Automatic."],
 customizer:["write","A WebServerFactoryCustomizer / Jackson2ObjectMapperBuilderCustomizer bean when properties aren't enough."],
 wsstart:["spring","Automatic."],
 runners:["write","An ApplicationRunner bean for startup work (warm caches, check config)."],
 avail:["spring","Read it via ApplicationAvailability; publish AvailabilityChangeEvent to mark the app broken."],
 shutdown:["config","server.shutdown (graceful default in 3.4+) and spring.lifecycle.timeout-per-shutdown-phase."],
 actauto:["config","Add spring-boot-starter-actuator."],
 exposure:["config","management.endpoints.web.exposure.include=health,info,metrics,prometheus"],
 health:["config","management.endpoint.health.show-details; your own HealthIndicator bean for custom checks."],
 dbhealth:["spring","Automatic when a DataSource exists."],
 probes:["config","management.endpoint.health.probes.enabled=true (automatic on Kubernetes)."],
 metrics:["config","Inject MeterRegistry for custom counters/timers; add micrometer-registry-prometheus for /actuator/prometheus."],
 app:["write","Your main class."],
 yml:["write","Your configuration files."],
 props:["write","Your @ConfigurationProperties record + @ConfigurationPropertiesScan."],
 yourbean:["write","Your @Bean methods."],
 mystarter:["write","An @AutoConfiguration class + the imports file in a shared library."]
};
var SECTIONS = ["CLASSPATH","ENVIRONMENT","BEAN DEFINITIONS","BEANS","WEB SERVER","EVENTS","HTTP","CONSOLE"];
