var SCENARIOS = [
// =====================================================================
{id:"launch", group:"Startup", name:"java -jar → main() → run() → Ready (the event timeline)",
 next:["core","startup",3,"What refresh() does inside"],
 goal:"What Boot does before, around and after the Spring container starts, in the exact event order.",
 steps:[
 {n:"jar",t:"The JVM starts the Boot launcher",w:"java -jar service-b.jar → org.springframework.boot.loader.launch.JarLauncher.main",
  d:["The jar was built by spring-boot-maven-plugin (repackage): your classes in BOOT-INF/classes, dependencies in BOOT-INF/lib.","The launcher creates a LaunchedClassLoader that can read the nested jars, then calls your Start-Class main()."],
  c:{"CLASSPATH|jar":"BOOT-INF/classes + BOOT-INF/lib/*.jar (spring-webmvc, tomcat-embed, hibernate, …)","CONSOLE|log":"(nothing yet)"},
  f:"Plain jar without repackage → 'no main manifest attribute'.",iv:"A Boot fat jar starts JarLauncher, which builds a class loader for the nested jars and then calls your main()."},
 {n:"main",t:"Your main() calls run",w:"SecurePayApplication.main → SpringApplication.run(SecurePayApplication.class, args)",d:[],c:{},f:"—",iv:"—"},
 {n:"sa",t:"SpringApplication is prepared",w:"new SpringApplication(primarySources) → WebApplicationType.deduceFromClasspath",
  d:["Servlet classes (spring-webmvc + a servlet container) on the classpath → SERVLET.","Loads ApplicationContextInitializers and ApplicationListeners from META-INF/spring.factories of all jars."],
  c:{"CLASSPATH|web type":"SERVLET"},f:"Both spring-webmvc and spring-webflux present → SERVLET wins; only webflux → REACTIVE.",iv:"Boot picks servlet vs reactive vs none purely from what's on the classpath."},
 {n:"listeners",t:"ApplicationStartingEvent",w:"SpringApplication.run → getRunListeners → listeners.starting",
  d:["Very first event: no Environment, no context yet.","LoggingApplicationListener only prepares logging here (beforeInitialize); logging.* settings are applied after the Environment is ready."],c:{"EVENTS|1":"ApplicationStartingEvent"},f:"—",iv:"—"},
 {n:"env",t:"Prepare the Environment",w:"SpringApplication.prepareEnvironment → getOrCreateEnvironment → configureEnvironment",
  d:["Adds command-line args, system properties and OS env vars as PropertySources."],c:{"ENVIRONMENT|sources":"commandLineArgs, systemProperties, systemEnvironment"},f:"—",iv:"—"},
 {n:"envpp",t:"EnvironmentPostProcessors run",w:"ApplicationEnvironmentPreparedEvent → EnvironmentPostProcessorApplicationListener.onApplicationEvent",
  d:["Loads every EnvironmentPostProcessor listed in spring.factories and calls postProcessEnvironment in order."],c:{},f:"—",iv:"—"},
 {n:"cfgdata",t:"Load application.yml",w:"ApplicationEnvironmentPreparedEvent → EnvironmentPostProcessorApplicationListener → ConfigDataEnvironmentPostProcessor",
  d:["Reads application.yml, then application-{profile}.yml for active profiles.","Now server.port, spring.datasource.url etc. are known."],
  c:{"EVENTS|2":"ApplicationEnvironmentPreparedEvent","ENVIRONMENT|sources":"commandLineArgs, systemProperties, systemEnvironment, application.yml","ENVIRONMENT|server.port":"8081"},
  f:"Invalid YAML → startup fails here with the file name and line.",iv:"Config files are loaded by an EnvironmentPostProcessor before any bean exists."},
 {n:"ctx",t:"Banner, then create the context",w:"printBanner → createApplicationContext (ApplicationContextFactory.DEFAULT)",
  d:["SERVLET → AnnotationConfigServletWebServerApplicationContext."],c:{"CONSOLE|log":"Spring Boot banner (v3.5.x)"},f:"—",iv:"—"},
 {n:"listeners",t:"Context prepared",w:"prepareContext → applyInitializers → contextPrepared → load(sources) → contextLoaded",
  d:["ApplicationContextInitializers run.","springApplicationArguments and the banner are registered as singletons, then load(sources) registers your main class as a bean definition.","Events: ApplicationContextInitializedEvent, ApplicationPreparedEvent."],
  c:{"EVENTS|3":"ApplicationContextInitializedEvent","EVENTS|4":"ApplicationPreparedEvent","BEAN DEFINITIONS|count":"internal processors + your main class"},f:"—",iv:"—"},
 {n:"ccpp",t:"refresh(): your config, then auto-config",w:"refreshContext → AbstractApplicationContext.refresh → ConfigurationClassPostProcessor",
  d:["Component scan from the main class's package, your @Bean methods, then AutoConfigurationImportSelector (see the auto-config scenario).","Tomcat is created in onRefresh; singletons are created; Tomcat starts listening in finishRefresh."],
  c:{"BEAN DEFINITIONS|count":"~350 (yours + matched auto-config)","WEB SERVER|state":"Tomcat started on port 8081"},f:"Most startup errors happen inside refresh().",iv:"—",
  z:[["core","startup",3,"refresh() step by step"]]},
 {n:"listeners",t:"ApplicationStartedEvent",w:"afterRefresh → 'Started SecurePayApplication in 2.3 seconds' → listeners.started",
  d:["Also publishes AvailabilityChangeEvent: LivenessState.CORRECT."],c:{"EVENTS|5":"ApplicationStartedEvent","CONSOLE|log":"Started SecurePayApplication in 2.3 seconds (process running for 2.6)"},f:"—",iv:"—"},
 {n:"runners",t:"Runners",w:"callRunners → ApplicationRunner.run / CommandLineRunner.run",d:["Ordered by @Order."],c:{},f:"Exception in a runner → startup fails and the app exits.",iv:"—"},
 {n:"listeners",t:"ApplicationReadyEvent",w:"listeners.ready",
  d:["Also AvailabilityChangeEvent: ReadinessState.ACCEPTING_TRAFFIC.","Safe point for 'app is fully up' work."],c:{"EVENTS|6":"ApplicationReadyEvent (readiness: ACCEPTING_TRAFFIC)"},f:"—",
  iv:"Event order: Starting → EnvironmentPrepared → ContextInitialized → Prepared → (refresh) → Started → runners → Ready; on error, ApplicationFailedEvent."}
 ]},
// =====================================================================
{id:"props", group:"Configuration", name:"Where does a property value come from? (order + profiles)",
 goal:"The same key in several places — which one wins, and how env vars map to property names.",
 steps:[
 {n:"yml",t:"Defaults in application.yml",w:"src/main/resources/application.yml",d:["spring.datasource.url: jdbc:h2:mem:payments","payment.max-amount: 5000"],
  c:{"ENVIRONMENT|spring.datasource.url":"jdbc:h2:mem:payments (application.yml)","ENVIRONMENT|payment.max-amount":"5000 (application.yml)"},f:"—",iv:"—"},
 {n:"profiles",t:"Activate the prod profile",w:"SPRING_PROFILES_ACTIVE=prod (env var)",d:["application-prod.yml is loaded after application.yml, so its values win."],
  c:{"ENVIRONMENT|active profiles":"[prod]"},f:"Typo in the profile name → no error, just defaults. Check the log line 'The following 1 profile is active: \"prod\"'.",iv:"—"},
 {n:"cfgdata",t:"Profile file overrides",w:"ConfigDataEnvironment → application-prod.yml",d:["spring.datasource.url: jdbc:postgresql://db:5432/payments"],
  c:{"ENVIRONMENT|spring.datasource.url":"jdbc:postgresql://db:5432/payments (application-prod.yml)"},f:"—",iv:"Profile-specific files override the default file; files outside the jar override files inside."},
 {n:"propsrc",t:"Environment variable beats both",w:"SystemEnvironmentPropertySource: SPRING_DATASOURCE_PASSWORD → spring.datasource.password",
  d:["Relaxed binding: upper case, dots → underscores, dashes removed.","This is how secrets are passed in containers, never committed in yml."],
  c:{"ENVIRONMENT|spring.datasource.password":"****** (OS env var)"},f:"—",iv:"Order (high → low): command line > system properties > env vars > profile yml > application.yml > defaults."},
 {n:"propsrc",t:"Command line beats everything",w:"java -jar app.jar --payment.max-amount=10000",d:[],c:{"ENVIRONMENT|payment.max-amount":"10000 (command line)"},f:"—",iv:"—"},
 {n:"binder",t:"Bound into the app",w:"Binder.bind(\"payment\", PaymentProperties.class)",d:["Your code sees maxAmount = 10000; it never knows which source won."],c:{"BEANS|paymentProperties":"maxAmount=10000"},f:"—",iv:"—"},
 {n:"report",t:"Find out who won",w:"GET /actuator/env/payment.max-amount (if exposed)",d:["Shows every source that defines the key and which one is active.","Since Boot 3.0 all values are shown as ****** by default (management.endpoint.env.show-values=NEVER); set WHEN_AUTHORIZED to see them as an admin."],c:{"HTTP|/actuator/env":"propertySources: commandLineArgs ✓, application.yml"},f:"Don't expose /actuator/env publicly.",iv:"—"}
 ]},
// =====================================================================
{id:"cfgprops", group:"Configuration", name:"@ConfigurationProperties binding and validation failure",
 goal:"Type-safe settings: bind a prefix to a record, validate it, and what the startup failure looks like.",
 steps:[
 {n:"props",t:"Your properties record",w:"@ConfigurationProperties(\"payment\") @Validated record PaymentProperties(@Positive BigDecimal maxAmount, @NotBlank String currency)",
  d:["Registered with @ConfigurationPropertiesScan on the main class (or @EnableConfigurationProperties)."],c:{"BEAN DEFINITIONS|paymentProperties":"PaymentProperties (constructor binding)"},f:"Not registered → NoSuchBeanDefinitionException where it's injected.",iv:"—"},
 {n:"binder",t:"Bind at creation",w:"ConfigurationPropertiesBeanRegistrar (definition + instance supplier) → ConstructorBound.from → ConfigurationPropertiesBinder.bindOrCreate → Binder.bindOrCreate",
  d:["A record is created with its constructor args from payment.*.","Relaxed names: payment.max-amount, PAYMENT_MAXAMOUNT both work.","Type conversion: \"5000\" → BigDecimal, \"30s\" → Duration."],
  c:{"BEANS|paymentProperties":"maxAmount=5000, currency=null"},f:"—",iv:"@ConfigurationProperties gives typed, validated, relaxed-bound settings; prefer it over many @Value fields."},
 {n:"props",t:"@Value vs @ConfigurationProperties",w:"@Value(\"${payment.max-amount}\") vs PaymentProperties",
  d:["@Value: one key, SpEL allowed, only limited relaxed binding (use the kebab-case name), no validation.","@ConfigurationProperties: a group of keys, full relaxed binding, @Validated, IDE auto-completion via spring-boot-configuration-processor (spring-configuration-metadata.json)."],c:{},f:"—",iv:"Use @Value for a single simple value; @ConfigurationProperties for anything structured or shared."},
 {n:"binder",t:"Validation fails",w:"ValidationBindHandler → BindValidationException",d:["currency is missing → @NotBlank violated."],c:{"BEANS|paymentProperties":"not created (invalid)"},f:"This is the failure path.",iv:"—"},
 {n:"failure",t:"Readable startup error",w:"FailureAnalyzers → BindValidationFailureAnalyzer",
  d:["APPLICATION FAILED TO START","Binding to target … failed: Property: payment.currency, Value: null, Reason: must not be blank","Action: Update your application's configuration."],
  c:{"CONSOLE|log":"APPLICATION FAILED TO START — payment.currency must not be blank"},f:"—",iv:"Invalid configuration fails at startup, not at the first request — fail fast."}
 ]},
// =====================================================================
{id:"autoconf", group:"Auto-configuration", name:"How a DataSource appears without you writing one",
 goal:"Starter on the classpath → candidate list → pre-filter → conditions → HikariDataSource built from properties.",
 steps:[
 {n:"starter",t:"You add a starter",w:"pom.xml: spring-boot-starter-data-jpa + com.h2database:h2",
  d:["The starter only pulls jars: spring-data-jpa, hibernate-core, HikariCP, spring-jdbc…","No code of yours mentions a DataSource."],c:{"CLASSPATH|jars":"HikariCP, hibernate-core, spring-data-jpa, h2"},f:"—",iv:"A starter is just a dependency bundle; the classpath is what triggers auto-configuration."},
 {n:"sba",t:"@EnableAutoConfiguration",w:"@SpringBootApplication → @EnableAutoConfiguration → @Import(AutoConfigurationImportSelector)",d:[],c:{},f:"—",iv:"—"},
 {n:"selector",t:"Deferred until your config is read",w:"ConfigurationClassParser → DeferredImportSelectorHandler → AutoConfigurationImportSelector.getAutoConfigurationEntry",
  d:["Your @Configuration classes and @Beans are registered first."],c:{"BEAN DEFINITIONS|yours":"registered"},f:"—",iv:"—"},
 {n:"imports",t:"Read the candidate list",w:"ImportCandidates.load(AutoConfiguration.class) → META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports",
  d:["~150 class names from spring-boot-autoconfigure (and any library's own file).","Minus exclusions (exclude = …, spring.autoconfigure.exclude)."],c:{"BEAN DEFINITIONS|candidates":"~150 auto-configurations"},f:"—",iv:"—"},
 {n:"filter",t:"Cheap pre-filter",w:"getConfigurationClassFilter().filter → OnClassCondition (metadata only)",
  d:["Classes not on the classpath (Mongo, Kafka, Redis…) are dropped without loading anything."],c:{"BEAN DEFINITIONS|candidates":"~60 left"},f:"—",iv:"—"},
 {n:"cond",t:"Full conditions on DataSourceAutoConfiguration",w:"@ConditionalOnClass(DataSource, EmbeddedDatabaseType) → PooledDataSourceConfiguration → DataSourceConfiguration.Hikari",
  d:["@ConditionalOnMissingBean(DataSource.class): you defined none → match.","@ConditionalOnClass(HikariDataSource) → Hikari chosen (first of Hikari, Tomcat, DBCP2…)."],c:{"BEAN DEFINITIONS|dataSource":"HikariDataSource (from DataSourceConfiguration.Hikari)"},
  f:"—",iv:"Auto-config = @Configuration classes guarded by conditions; @ConditionalOnMissingBean is what lets your bean win."},
 {n:"dsauto",t:"Bean built from properties",w:"DataSourceConfiguration.Hikari.dataSource(properties, JdbcConnectionDetails) → DataSourceBuilder → HikariDataSource",
  d:["No URL set and H2 on the classpath → embedded jdbc:h2:mem:<uuid>.","Since Boot 3.1 the URL/user/password come through a JdbcConnectionDetails bean (default: from properties). Testcontainers @ServiceConnection or Docker Compose support provide their own ConnectionDetails — that's how tests get a real Postgres without properties.","spring.datasource.hikari.* bound onto the pool."],c:{"BEANS|dataSource":"HikariDataSource (HikariPool-1)"},f:"No URL and no embedded DB → 'Failed to configure a DataSource: url attribute is not specified'.",iv:"—"},
 {n:"jpaauto",t:"Dependent auto-configs follow",w:"@AutoConfiguration(after = DataSourceAutoConfiguration.class) → HibernateJpaAutoConfiguration",
  d:["Ordering attributes make JPA config see the DataSource.","Creates EntityManagerFactory and JpaTransactionManager."],c:{"BEANS|entityManagerFactory":"LocalContainerEntityManagerFactoryBean","BEANS|transactionManager":"JpaTransactionManager"},f:"—",iv:"—"},
 {n:"report",t:"Check what happened",w:"--debug → CONDITIONS EVALUATION REPORT",
  d:["Positive matches: DataSourceAutoConfiguration matched: @ConditionalOnClass found required classes…","Negative matches: MongoAutoConfiguration: did not match: required class not found."],
  c:{"CONSOLE|log":"CONDITIONS EVALUATION REPORT (positive / negative matches)"},f:"—",iv:"'Why isn't my bean created?' → run with --debug and read the conditions report."}
 ]},
// =====================================================================
{id:"override", group:"Auto-configuration", name:"Your bean replaces Boot's default (back-off)",
 goal:"Defining your own ObjectMapper / PasswordEncoder / SecurityFilterChain makes the matching auto-config step aside.",
 steps:[
 {n:"yourbean",t:"You define a SecurityFilterChain",w:"@Bean SecurityFilterChain api(HttpSecurity http) in your SecurityConfig",d:["Registered in the first pass, before auto-config is evaluated."],c:{"BEAN DEFINITIONS|api":"SecurityFilterChain (yours)"},f:"—",iv:"—"},
 {n:"secauto",t:"Default chain backs off",w:"SpringBootWebSecurityConfiguration.defaultSecurityFilterChain → @ConditionalOnDefaultWebSecurity → no match",
  d:["The condition is 'no SecurityFilterChain bean exists'. Yours exists → Boot's default chain is not created.","Without yours, the default is: everything authenticated + form login + basic; or, when issuer-uri/jwk-set-uri is set, everything authenticated + oauth2ResourceServer(jwt)."],c:{"BEAN DEFINITIONS|defaultSecurityFilterChain":"SKIPPED (you have one)"},f:"—",iv:"—"},
 {n:"secauto",t:"Generated user also backs off",w:"UserDetailsServiceAutoConfiguration → @ConditionalOnMissingBean(…, type = JwtDecoder …)",
  d:["UserDetailsServiceAutoConfiguration also has @ConditionalOnMissingClass checks: just having the OAuth2 resource-server / client / SAML classes on the classpath (e.g. OpaqueTokenIntrospector) stops the generated user — unless spring.security.user.name/password are set.","So with oauth2-resource-server there's no in-memory 'user' and no generated password in the log."],c:{"CONSOLE|log":"(no 'Using generated security password')"},f:"Without any security config you'd see 'Using generated security password: …' and every endpoint needs login.",iv:"—"},
 {n:"rsauto",t:"Resource server gives you a JwtDecoder",w:"OAuth2ResourceServerAutoConfiguration → OAuth2ResourceServerJwtConfiguration → SupplierJwtDecoder",
  d:["Because issuer-uri is set and you defined no JwtDecoder bean.","It resolves the issuer's JWK Set on first use, so startup doesn't need the Auth Server running."],c:{"BEANS|jwtDecoder":"SupplierJwtDecoder (issuer http://localhost:9000)"},f:"—",iv:"—"},
 {n:"cond",t:"Order matters for @ConditionalOnMissingBean",w:"OnBeanCondition evaluated at REGISTER_BEAN phase",
  d:["Works reliably in auto-configurations because they're processed after your beans.","In your own normal @Configuration, @ConditionalOnMissingBean depends on processing order — avoid it there."],c:{},f:"—",iv:"@ConditionalOnMissingBean is meant for auto-configuration classes, not ordinary config."},
 {n:"jacksonauto",t:"Boot's ObjectMapper",w:"JacksonAutoConfiguration → Jackson2ObjectMapperBuilder → objectMapper (@ConditionalOnMissingBean)",
  d:["Registers modules (JavaTime, Jdk8, ParameterNames), applies spring.jackson.*, then every Jackson2ObjectMapperBuilderCustomizer bean."],c:{"BEANS|objectMapper":"Boot's (JavaTimeModule …)"},f:"—",iv:"—"},
 {n:"customizer",t:"Tweak instead of replace",w:"Jackson2ObjectMapperBuilderCustomizer / WebServerFactoryCustomizer beans",
  d:["Replacing ObjectMapper entirely loses Boot's settings (modules, spring.jackson.*).","A customizer adds to Boot's object instead."],c:{"BEANS|objectMapper":"Boot's, plus your customizer"},f:"@EnableWebMvc on a config class → Boot's WebMvcAutoConfiguration backs off completely (lost converters/static config).",
  iv:"Prefer properties, then customizers, then full replacement."}
 ]},
// =====================================================================
{id:"tomcat", group:"Startup", name:"Embedded Tomcat: create, register servlets/filters, start (port in use)",
 goal:"How the web server is part of the Spring context and when it actually starts listening.",
 steps:[
 {n:"webauto",t:"Factory bean",w:"ServletWebServerFactoryAutoConfiguration → EmbeddedTomcat → TomcatServletWebServerFactory",d:["server.port=8081 applied by a customizer (ServletWebServerFactoryCustomizer)."],c:{"BEANS|webServerFactory":"TomcatServletWebServerFactory(port=8081)"},f:"—",iv:"—"},
 {n:"wsf",t:"Tomcat created during refresh()",w:"ServletWebServerApplicationContext.onRefresh → createWebServer → factory.getWebServer(initializers)",
  d:["Happens before most singletons are created (onRefresh comes before finishBeanFactoryInitialization) — but Filter/registration beans, and whatever they inject, are created early here.","ServletContextInitializers run: DispatcherServletRegistrationBean, filter registrations (incl. springSecurityFilterChain via DelegatingFilterProxyRegistrationBean)."],
  c:{"WEB SERVER|state":"created, connectors not bound","WEB SERVER|servlets":"dispatcherServlet → /","WEB SERVER|filters":"characterEncoding, formContent, requestContext, springSecurityFilterChain"},f:"—",
  iv:"Boot registers the DispatcherServlet and filters into embedded Tomcat through ServletContextInitializer beans — no web.xml."},
 {n:"mvcauto",t:"DispatcherServlet bean",w:"DispatcherServletAutoConfiguration → dispatcherServlet + DispatcherServletRegistrationBean",d:["Initialised lazily on the first request by default (spring.mvc.servlet.load-on-startup=-1)."],c:{},f:"—",iv:"—"},
 {n:"wsstart",t:"Start listening",w:"finishRefresh → WebServerStartStopLifecycle.start → TomcatWebServer.start",
  d:["Connectors bound only after ALL beans are created, so no request can hit a half-built app."],c:{"WEB SERVER|state":"listening on 8081","CONSOLE|log":"Tomcat started on port 8081 (http) with context path '/'"},
  f:"Port busy → PortInUseException → 'Web server failed to start. Port 8081 was already in use.' + Action: identify and stop the process or change server.port.",iv:"Tomcat is created early in refresh() but only starts accepting connections at the end."},
 {n:"customizer",t:"Virtual threads (Boot 3.2+, Java 21)",w:"spring.threads.virtual.enabled=true",
  d:["Tomcat handles each request on a virtual thread; @Async and scheduling use virtual threads too.","The limit moves to the connection pool: thousands of requests can now wait on 10 Hikari connections.","Watch for pinning (synchronized blocks around blocking I/O on older JDKs)."],c:{"WEB SERVER|threads":"virtual (if enabled)"},f:"—",iv:"Virtual threads remove the thread-pool limit, not the database limit."},
 {n:"shutdown",t:"Graceful stop",w:"SpringApplicationShutdownHook → context.close → WebServerGracefulShutdownLifecycle",
  d:["First readiness → REFUSING_TRAFFIC (AvailabilityChangeEvent), then lifecycles stop: WebServerGracefulShutdownLifecycle stops new requests and lets in-flight ones finish (up to 30 s), then beans are destroyed, then Tomcat is destroyed."],c:{"WEB SERVER|state":"stopped"},f:"kill -9 skips all of this.",iv:"—"}
 ]},
// =====================================================================
{id:"fail", group:"Startup", name:"APPLICATION FAILED TO START (missing bean)",
 goal:"How a wiring error becomes the readable failure report.",
 steps:[
 {n:"ccpp",t:"Your service needs a bean nobody defines",w:"PaymentService(PaymentGateway gateway) — no PaymentGateway bean (class outside the scanned package)",d:[],c:{"BEAN DEFINITIONS|paymentGateway":"missing"},f:"—",iv:"—",
  z:[["core","di-fail",1,"How Spring resolves the dependency"]]},
 {n:"ctx",t:"refresh() throws",w:"preInstantiateSingletons → UnsatisfiedDependencyException → NoSuchBeanDefinitionException",d:["Context closes; beans already created are destroyed."],c:{"BEANS|state":"context closed"},f:"This is the failure path.",iv:"—"},
 {n:"listeners",t:"ApplicationFailedEvent",w:"SpringApplication.handleRunFailure → listeners.failed",d:[],c:{"EVENTS|failed":"ApplicationFailedEvent"},f:"—",iv:"—"},
 {n:"failure",t:"The report",w:"FailureAnalyzers → NoSuchBeanDefinitionFailureAnalyzer",
  d:["Description: Parameter 0 of constructor in PaymentService required a bean of type 'PaymentGateway' that could not be found.","Action: Consider defining a bean of type 'PaymentGateway' in your configuration.","It also lists auto-configured beans of that type that did not match and why."],
  c:{"CONSOLE|log":"APPLICATION FAILED TO START — Description / Action"},f:"—",iv:"Read the Description and Action first; the long stack trace below it is usually just the path to the same error."},
 {n:"app",t:"Common real cause",w:"Main class package vs bean package",d:["@SpringBootApplication in com.securepay; bean in com.gateway → not scanned.","Fix: move it under com.securepay or add scanBasePackages."],c:{},f:"—",iv:"—"}
 ]},
// =====================================================================
{id:"actuator", group:"Actuator", name:"GET /actuator/health (and when it returns 503)",
 goal:"Health aggregation, exposure, security, and the database check.",
 steps:[
 {n:"actauto",t:"Actuator on the classpath",w:"spring-boot-starter-actuator → EndpointAutoConfiguration, HealthEndpointAutoConfiguration",d:["Endpoints are beans; only health is exposed over HTTP by default."],c:{"HTTP|exposed":"/actuator/health"},f:"—",iv:"—"},
 {n:"exposure",t:"Choose what's visible",w:"management.endpoints.web.exposure.include=health,info,metrics",d:["Each exposed endpoint gets a web mapping under /actuator."],c:{"HTTP|exposed":"/actuator/health, /actuator/info, /actuator/metrics"},f:"include=* in production exposes env, beans, heapdump.",iv:"—"},
 {n:"health",t:"Request passes security first",w:"Your SecurityFilterChain: requestMatchers(\"/actuator/health/**\").permitAll()",
  d:["Actuator endpoints are normal MVC endpoints behind your filter chain.","Load balancers/Kubernetes call health without a token, so it must be permitted."],c:{"HTTP|request":"GET /actuator/health (no token)"},f:"Not permitted → 401, and the load balancer marks the instance dead.",iv:"Permit /actuator/health in your SecurityFilterChain; secure the rest."},
 {n:"health",t:"Aggregate contributors",w:"HealthEndpointWebExtension → HealthEndpointSupport → CompositeHealthContributor",d:["Asks db, diskSpace, ping… then SimpleStatusAggregator picks the worst status."],c:{},f:"—",iv:"—"},
 {n:"dbhealth",t:"Database check",w:"DataSourceHealthIndicator.doHealthCheck → Connection.isValid / validation query",d:["Database down → DOWN."],c:{"HTTP|db":"DOWN (connection refused)"},f:"—",iv:"—"},
 {n:"health",t:"HTTP status from health",w:"HttpCodeStatusMapper: DOWN / OUT_OF_SERVICE → 503, UP → 200",
  d:["Body shows only {\"status\":\"DOWN\"} unless show-details is set."],c:{"HTTP|response":"503 {\"status\":\"DOWN\"}"},f:"—",iv:"Health returns 503 when DOWN so load balancers stop routing to the instance."},
 {n:"exposure",t:"Separate management port",w:"management.server.port=9091",
  d:["Actuator runs in a child context on its own port: keep it internal (not exposed through the load balancer) while the app port stays public.","Probes can also be added to the main port with management.endpoint.health.probes.add-additional-paths=true (/livez, /readyz)."],c:{"HTTP|management port":"9091"},f:"—",iv:"—"},
 {n:"metrics",t:"Metrics next to health",w:"/actuator/metrics/http.server.requests, hikaricp.connections.active",d:["Micrometer records every request and the pool usage automatically."],c:{"HTTP|metrics":"http.server.requests, jvm.memory.used, hikaricp.connections.active"},f:"—",iv:"—"}
 ]},
// =====================================================================
{id:"probes", group:"Actuator", name:"Liveness vs readiness (Kubernetes)",
 goal:"Two different questions: 'restart me?' and 'send me traffic?' — driven by ApplicationAvailability.",
 steps:[
 {n:"probes",t:"Enable probe groups",w:"management.endpoint.health.probes.enabled=true (automatic on Kubernetes and Cloud Foundry)",d:["/actuator/health/liveness and /actuator/health/readiness."],c:{"HTTP|probes":"/liveness, /readiness"},f:"—",iv:"—"},
 {n:"avail",t:"Started → live",w:"ApplicationStartedEvent → AvailabilityChangeEvent(LivenessState.CORRECT)",d:[],c:{"EVENTS|liveness":"CORRECT"},f:"—",iv:"—"},
 {n:"avail",t:"Ready → accept traffic",w:"ApplicationReadyEvent → AvailabilityChangeEvent(ReadinessState.ACCEPTING_TRAFFIC)",d:["Kubernetes starts sending requests only now."],c:{"EVENTS|readiness":"ACCEPTING_TRAFFIC"},f:"—",iv:"—"},
 {n:"dbhealth",t:"DB down: which probe fails?",w:"By default the db check is NOT part of liveness or readiness groups",
  d:["Liveness failing would restart the pod — useless if the DB is the problem.","Add it to readiness only if you want to stop traffic: management.endpoint.health.group.readiness.include=readinessState,db"],c:{},f:"Putting external checks in liveness → restart storms when the DB blips.",iv:"Liveness = is the process broken (restart); readiness = can it serve now (route traffic). Keep external dependencies out of liveness."},
 {n:"shutdown",t:"Graceful shutdown flips readiness",w:"context close → ReadinessState.REFUSING_TRAFFIC → in-flight requests finish",d:[],c:{"EVENTS|readiness":"REFUSING_TRAFFIC"},f:"—",iv:"—"}
 ]},
// =====================================================================
{id:"mystarter", group:"Auto-configuration", name:"Write your own auto-configuration (shared library)",
 goal:"How a company 'common-security' or 'audit' library configures itself in every service — the same mechanism Boot uses.",
 steps:[
 {n:"mystarter",t:"The auto-config class",w:"@AutoConfiguration @ConditionalOnClass(RestClient.class) @EnableConfigurationProperties(AuditProperties.class) class AuditAutoConfiguration",
  d:["@Bean @ConditionalOnMissingBean AuditClient auditClient(AuditProperties p) — so a service can still override it."],c:{"CLASSPATH|library":"audit-spring-boot-starter"},f:"—",iv:"—"},
 {n:"imports",t:"Register it",w:"src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports",
  d:["One line: com.securepay.audit.AuditAutoConfiguration","Boot 2's spring.factories EnableAutoConfiguration key is no longer read (removed in 3.0)."],c:{"BEAN DEFINITIONS|candidates":"+ AuditAutoConfiguration"},f:"Forgetting the file → nothing happens, no error.",iv:"Own auto-config: @AutoConfiguration class + the AutoConfiguration.imports file + conditions."},
 {n:"selector",t:"Picked up like Boot's own",w:"AutoConfigurationImportSelector reads every jar's imports file",d:["Not component-scanned; keep it outside the app's scan packages."],c:{},f:"—",iv:"—"},
 {n:"cond",t:"Conditions decide per service",w:"@ConditionalOnProperty(prefix = \"audit\", name = \"enabled\", matchIfMissing = true)",d:["Service can turn it off with audit.enabled=false."],c:{"BEANS|auditClient":"created (audit.enabled not set)"},f:"—",iv:"—"},
 {n:"starter",t:"The starter module",w:"audit-spring-boot-starter (pom only) → depends on audit-autoconfigure + libraries",d:["Services add one dependency, like any Boot starter."],c:{},f:"—",iv:"Starter = dependencies; autoconfigure module = the @AutoConfiguration classes."}
 ]},
// =====================================================================
{id:"tests", group:"Auto-configuration", name:"Tests: @SpringBootTest vs slices, @MockitoBean",
 goal:"How tests reuse auto-configuration: full context vs a slice, and why test startup is sometimes slow.",
 steps:[
 {n:"ctx",t:"@SpringBootTest = the whole app",w:"SpringBootTestContextBootstrapper → SpringApplication (test) → full auto-configuration",
  d:["Every bean, the real DataSource, security… webEnvironment = MOCK by default (no real port), RANDOM_PORT for real HTTP."],c:{"BEANS|context":"full application context"},f:"—",iv:"—"},
 {n:"selector",t:"Slices load only part of auto-config",w:"@WebMvcTest(PaymentController.class) → @ImportAutoConfiguration (only MVC-related auto-configs)",
  d:["@WebMvcTest: controllers, advice, converters, filters, security — no services, no JPA. You mock the service.","@DataJpaTest: JPA + embedded DB + transactions (rolled back per test), no web."],c:{"BEANS|context":"MVC slice (controller + web infrastructure)"},f:"Controller needs a service bean that isn't mocked → NoSuchBeanDefinitionException in the test.",iv:"Slices are auto-config filtered by test annotation: faster and focused."},
 {n:"yourbean",t:"Replace a bean with a mock",w:"@MockitoBean PaymentService paymentService (Spring Framework 6.2; replaces Boot's deprecated @MockBean)",d:["The mock replaces the bean in the context."],c:{"BEANS|paymentService":"Mockito mock"},f:"—",iv:"—"},
 {n:"ctx",t:"Context caching",w:"TestContext framework caches contexts by configuration key",
  d:["Tests with the same configuration reuse one context; every different @MockitoBean set / properties / profile creates a new context.","Many slightly different test setups = many contexts = slow build."],c:{},f:"—",iv:"Keep test configurations uniform so the context cache is reused."}
 ]},
{id:"startupspeed", group:"Startup", name:"Faster startup: lazy initialization, AOT and native image",
 goal:"Trade-offs when startup time matters (serverless, scale-to-zero).",
 steps:[
 {n:"ctx",t:"Lazy initialization",w:"spring.main.lazy-initialization=true",
  d:["Beans are created on first use instead of at startup.","Faster start, but wiring errors appear at the first request and the first requests are slow."],c:{"BEANS|creation":"on first use"},f:"A broken bean is discovered in production traffic instead of at startup.",iv:"Lazy init trades fail-fast startup for speed; keep it off for normal services."},
 {n:"cond",t:"AOT processing",w:"mvn spring-boot:process-aot / native build",
  d:["At build time Boot evaluates conditions and generates bean definitions as code (no reflection-heavy scanning at startup).","Closed world: conditions and profiles are fixed at build time — you can't switch auto-config with a runtime property."],c:{"BEAN DEFINITIONS|source":"generated code (AOT)"},f:"—",iv:"—"},
 {n:"jar",t:"GraalVM native image",w:"mvn -Pnative native:compile",d:["Starts in tens of milliseconds, low memory; long build, reflection needs hints."],c:{"CLASSPATH|artifact":"native executable"},f:"—",iv:"Native image = AOT + closed-world assumptions; fast start, slower builds, fewer dynamic tricks."}
 ]}
];