// Who is responsible for each box in YOUR code.
// spring = Spring creates it, you don't touch it | config = appears because of a bean / DSL line / property you write
// write  = a class you write yourself            | ext    = outside your code
var OWN = {
 client:["ext","Postman, the browser, or your React app. Not Spring code."],
 response:["spring","Written by whichever filter/handler finished the request. You only shape it through handlers or the controller's return value."],
 dfp:["spring","Registered by Spring Boot auto-configuration (SecurityFilterAutoConfiguration) once spring-boot-starter-security is on the classpath. You never write it."],
 fcp:["config","Built from YOUR SecurityFilterChain @Bean method(s) that take HttpSecurity. More than one chain → give each @Order and a securityMatcher (your Auth Server has two)."],
 fw:["spring","StrictHttpFirewall by default. Almost never customised."],
 f_ctx:["spring","Always present. You never configure it."],
 f_hdr:["config","On by default. Change only with http.headers(...), e.g. frameOptions sameOrigin for the H2 console."],
 f_cors:["config","Only there if you call http.cors(...) and define a CorsConfigurationSource @Bean (allowed origins, methods, headers). Needed when a browser app on another origin calls your API."],
 f_csrf:["config","On by default. For Bearer-token APIs (Service A/B) you turn it off in the DSL. Keep it on for form login (Auth Server)."],
 f_logout:["config","On by default at POST /logout. http.logout(...) only to change the URL or success page."],
 f_upaf:["config","Added by http.formLogin(...). With a custom loginPage(\"/login\") you also write the login controller and HTML page."],
 f_basic:["config","Added by http.httpBasic(...)."],
 f_bearer:["config","Added by http.oauth2ResourceServer(o -> o.jwt(...)) plus the property spring.security.oauth2.resourceserver.jwt.issuer-uri."],
 f_reqcache:["spring","Always present; works with formLogin automatically."],
 f_anon:["spring","Always present."],
 f_etf:["spring","Always present. You only plug in your own entry point / denied handler through http.exceptionHandling(...)."],
 f_authz:["config","Your MAIN job: http.authorizeHttpRequests(...) with requestMatchers(HTTP method, path) → hasAuthority(\"SCOPE_…\") / hasRole / permitAll, ending with anyRequest().authenticated()."],
 holder:["spring","You only READ it: @AuthenticationPrincipal in a controller, or SecurityContextHolder.getContext().getAuthentication() in a service."],
 repo:["config","Chosen by your session setting: sessions (default, form login) or http.sessionManagement(... STATELESS) for APIs."],
 session:["spring","Tomcat's HttpSession. Timeout via server.servlet.session.timeout."],
 reqstore:["spring","Default HttpSessionRequestCache; nothing to write."],
 mgr:["spring","Built for you from your UserDetailsService + PasswordEncoder beans, or by oauth2ResourceServer. Expose it as a @Bean only if YOUR code calls authenticate() (e.g. a custom JSON login endpoint)."],
 p_dao:["spring","Created automatically when a UserDetailsService bean and a PasswordEncoder bean exist."],
 p_jwt:["spring","Created by oauth2ResourceServer().jwt()."],
 p_client:["spring","Authorization Server internal. Driven by your RegisteredClientRepository + PasswordEncoder."],
 p_codereq:["spring","Authorization Server internal. Behaviour set by your RegisteredClient (redirect URIs, scopes, requireAuthorizationConsent, requireProofKey)."],
 p_code:["spring","Authorization Server internal."],
 p_cc:["spring","Authorization Server internal. Works only if the client has the CLIENT_CREDENTIALS grant in your RegisteredClient."],
 p_refresh:["spring","Authorization Server internal. Needs the REFRESH_TOKEN grant; reuse/rotation set in TokenSettings."],
 enc:["config","A @Bean PasswordEncoder, usually the delegating one from PasswordEncoderFactories."],
 uds:["config","A @Bean UserDetailsService. Now: InMemoryUserDetailsManager. Real app: YOUR class implementing UserDetailsService with a JPA repository (then it becomes 'you write')."],
 db:["ext","Your tables. JdbcUserDetailsManager expects users/authorities; a custom UserDetailsService can use any schema."],
 decoder:["config","Auto-created from the issuer-uri property. Write your own @Bean JwtDecoder only to add validators (e.g. audience)."],
 jwks:["spring","Served by the Authorization Server at /oauth2/jwks from your JWKSource bean."],
 rcr:["config","A @Bean RegisteredClientRepository: InMemory now, JdbcRegisteredClientRepository later. Each client = id, secret, grant types, redirect URIs, scopes, token settings."],
 authsvc:["spring","In-memory by default. Production: define a JdbcOAuth2AuthorizationService @Bean (SAS ships the table schema)."],
 consent:["spring","In-memory by default. Production: JdbcOAuth2AuthorizationConsentService @Bean."],
 gen:["config","You provide a @Bean JWKSource (RSA key pair + kid). Extra claims: a @Bean OAuth2TokenCustomizer<JwtEncodingContext>. The generator itself is automatic."],
 azmgr:["config","Built from YOUR authorizeHttpRequests rules and @PreAuthorize expressions."],
 entry:["config","Picked automatically by formLogin / httpBasic / oauth2ResourceServer. Custom JSON 401 → YOUR class implementing AuthenticationEntryPoint, registered via http.exceptionHandling(...)."],
 denied:["config","Picked automatically. Custom JSON 403 → YOUR class implementing AccessDeniedHandler, registered via http.exceptionHandling(...)."],
 as_authz:["config","Added by the Authorization Server configurer in your @Order(1) chain (OAuth2AuthorizationServerConfigurer.authorizationServer() applied with http.with(...)) + an AuthorizationServerSettings @Bean."],
 as_client:["config","Same Authorization Server configurer as above; nothing extra to write."],
 as_token:["config","Same Authorization Server configurer as above; nothing extra to write."],
 ds:["spring","Spring MVC; auto-configured by Boot."],
 ctrl:["write","Your @RestController. Take the caller from the token (@AuthenticationPrincipal Jwt → getSubject()), never from the request body."],
 msec:["config","@EnableMethodSecurity on a @Configuration class + @PreAuthorize(\"…\") on your methods."],
 wc:["write","Your WebClient @Bean built with ServletBearerExchangeFilterFunction as a filter, plus your client class that calls Service B."],
 svcb:["write","Your second Spring Boot app; same resource-server config as above."],
 logouth:["spring","Default handlers; nothing to write."]
};
